### ISSUE TITLE
SystemError: initialization of aimssip raised unreported exception (when compiled with CLang)

### ISSUE THREAD

**Issue by ylep** [brainvisa/aims-free#27]
Under Python 3, a `SystemError` exception is thrown upon importing `aims.soma.aimssip`. The issue occurs on my laptop, even after re-compiling the whole BrainVISA tree from scratch, whereas it does not occur on my workstation (both have similar Ubuntu 16.04 setup).

```
$ /volatile/bv/build/bug_fix_py3/bin/bv_env python3 -c 'import soma.aims'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/volatile/bv/build/bug_fix_py3/python/soma/aims/__init__.py", line 121, in <module>
    from soma.aims import aimssip
SystemError: initialization of aimssip raised unreported exception
```

**Comment by ylep** [comment]
Thanks to 2b9fa9950f57170c8e67fd1feff6a99538bd8b2b we now have a clearer error message:

```$ /volatile/bv/build/bug_fix_py3/bin/bv_env python3 -c 'import soma.aims'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/volatile/bv/build/bug_fix_py3/python/soma/aims/__init__.py", line 122, in <module>
    from soma.aims import aimssip
ImportError: numpy.core.multiarray failed to import
```

**Comment by ylep** [comment]
Sigh. Finally tracked down this issue which wasted my day. The undefined
behaviour occurred because `npy_import_array` was missing a return statement in
the success case. This is technically undefined behaviour, so the compiler is
allowed to do whatever it wants, although the return value is completely
ignored. CLang 6.0.0 feels like it is being clever and changes the code path in
this case, taking the error path, which raised the Python exeception.

Sigh.
