### ISSUE TITLE
Issue with I/O of RGBA Volumes

### ISSUE THREAD

**Issue by denisri** [brainvisa/aims-free#73]
### Discussed in https://github.com/brainvisa/brainvisa.github.io/discussions/89

<div type='discussions-op-text'>

<sup>Originally posted by **c-langlet** November 30, 2021</sup>
Hello,

I have an issue with I/O of RGBA Volumes : I write a RGBA Volume in a png file, and when I read it back it is read as a Volume_U32. 
Any idea ? I used to do that and it was working. I changed some things in my code and doubled check but I don't think that I touched to this part, and anyway the small example following is done outside of the code. 

Example : 

```
>>> arr
array([[[[[ 20,  20,  20, 255]]]],
       [[[[  0,   0,   0, 255]]]],
       [[[[  0,   0,   0, 255]]]],
       ...,
       [[[[ 60,  60,  60, 255]]]],
       [[[[ 60,  60,  60, 255]]]],
       [[[[ 80,  80,  80, 255]]]]], dtype=uint8)
>>> vol = aims.Volume('RGBA', arr.shape[0])
>>> vol
<soma.aims.Volume_RGBA object at 0x7fada28b3ee8>
>>> vol['v'] = arr
>>> vol['v']
array([[[[[ 20,  20,  20, 255]]]],
       [[[[  0,   0,   0, 255]]]],
       [[[[  0,   0,   0, 255]]]],
       ...,
       [[[[ 60,  60,  60, 255]]]],
       [[[[ 60,  60,  60, 255]]]],
       [[[[ 80,  80,  80, 255]]]]], dtype=uint8)
>>> aims.write(vol, '/volatile/clanglet/tmp/test.png')
>>> vol2 = aims.read('/volatile/clanglet/tmp/test.png')
>>> vol2
<soma.aims.Volume_U32 object at 0x7facef16edc8>
>>> vol2['v']
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/casa/host/build/python/soma/aims/__init__.py", line 984, in <lambda>
    numpy.asarray(self).__getitem__(*args, **kwargs)
IndexError: only integers, slices (`:`), ellipsis (`...`), numpy.newaxis (`None`) and integer or boolean arrays are valid indices
>>> vol2.np
array([[[[20]]],
       [[[ 0]]],
       [[[ 0]]],
       ...,
       [[[60]]],
       [[[60]]],
       [[[80]]]], dtype=uint32)

```</div>

**Comment by denisri** [comment]
OK it's the detection of data type when reading a PNG file which is not robust: PNG (and a bunch of other 2D formats) is read using Qt. The API doesn't distinguish between scalar (gray levels) or RGB images, as for Qt they are all read as RGBA anyway. Thus we used the `QImage::allGray()` method, which thus determines the data type from the contents values.
I will rather use the `QImage::hasAlphaChannel()` first, thus if alpha is present, we will use the RGBA type in priority. It's still not completely consistent, but it's difficult do do better (unless always use RGB/RGBA types).
