### ISSUE TITLE
pyaims_io tests are broken in both 5.1 and master branches

### ISSUE THREAD

**Issue by denisri** [brainvisa/aims-free#94]
**Describe the bug**
nightly tests fail in `soma.aims.tests.test_pyaims_io` with the error:
```
======================================================================
ERROR: test_io_with_strides (__main__.TestPyaimsIO)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/casa/host/build/python/soma/aims/tests/test_pyaims_io.py", line 729, in test_io_with_strides
    failing_files.update(self.use_format(vol, format, view, options))
  File "/casa/host/build/python/soma/aims/tests/test_pyaims_io.py", line 186, in use_format
    self.assertTrue(compare_images(vol4, vol3,
  File "/casa/host/build/python/soma/aims/volumetools.py", line 213, in compare_images
    raise RuntimeError(msg + ', max diff: %f, max allowed: %f'
RuntimeError: comparing sub-volume Volume_S16 (write, format .nii) and patially read, max diff: 0.000000, max allowed: 0.000001
```
They were OK when we released 5.1.0 so it is a new regression, or a corrupted memory which shows up randomly.

**Comment by denisri** [comment]
The problem apparently appeared in a2941046b43b95299f298a0366d59b3dae55c325, which was a fix for a wrongly oriented array. I have to investigate further.
